<a href="https://colab.research.google.com/github/Snigdho2005/Complete-Machine-Learning-in-Python/blob/main/Complete_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

In [ ]:
!pip install numpy

In [ ]:
from time import process_time

List vs Numpy - Time Taken

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0005420249999978921


In [ ]:
import numpy as np

np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00018377199999974891


Numpy Arrays

In [ ]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# Creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in Numpy Arrays

In [ ]:
 # create a numpy array of Zeros
 x = np.zeros((4,5))
 print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.79851068 0.51697918 0.6661523  0.38449465]
 [0.01346238 0.28801145 0.31425334 0.74334069]
 [0.4003939  0.40459392 0.70657406 0.17925607]]


In [ ]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[68 26 75 12 20]
 [89 60 35 15 73]
 [23 91 40 43 22]]


In [ ]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analyse a Numpy Array

In [ ]:
import numpy as np
c = np.random.randint(10,90,(5,5))
print(c)

[[58 81 43 48 13]
 [70 80 11 25 68]
 [47 11 55 51 26]
 [71 62 61 59 72]
 [52 79 41 41 65]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
# checking the data type of values in the array
print(c.dtype)

int64


Mathematical Operations on a NP Array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[1 0 8]
 [9 4 9]
 [3 5 4]]
[[15 18 16]
 [10 11 13]
 [14 19 16]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[16 18 24]
 [19 15 22]
 [17 24 20]]
[[-14 -18  -8]
 [ -1  -7  -4]
 [-11 -14 -12]]
[[ 15   0 128]
 [ 90  44 117]
 [ 42  95  64]]
[[0.06666667 0.         0.5       ]
 [0.9        0.36363636 0.69230769]
 [0.21428571 0.26315789 0.25      ]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[9 5 7]
 [6 7 9]
 [9 2 3]]
[[14 14 12]
 [18 16 18]
 [16 17 17]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[23 19 19]
 [24 23 27]
 [25 19 20]]
[[ -5  -9  -5]
 [-12  -9  -9]
 [ -7 -15 -14]]
[[126  70  84]
 [108 112 162]
 [144  34  51]]
[[0.64285714 0.35714286 0.58333333]
 [0.33333333 0.4375     0.5       ]
 [0.5625     0.11764706 0.17647059]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 6 0]
 [9 2 4]]
(2, 3)


In [ ]:
# Transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[4 9]
 [6 2]
 [0 4]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 8 7]
 [1 0 2]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[1 1]
 [8 0]
 [7 2]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 1 0]
 [5 4 2]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 1]
 [0 5]
 [4 2]]
(3, 2)
